#define WIDTH       700
#define HEIGHT      700
#define WINDOWX     300
#define WINDOWY     100
#define BACKGROUNDX 0
#define BACKGROUNDY 0
#define NUMBERX     -50
#define NUMBERSY    140
#define FIRSTPIECEX 80
#define FIRSTPIECEY 140
#define PIECESIZE   51
#define MAXPLAYS    10
#define MAXBOARD    8
#define BOARDCORR   32
#define EXTRAPOS    10
#define COLORSY     140
#define COLORSXSIZE 40
#define COLORSYSIZE 500
#define MAX_LEVELS  5
#define MAXSTR      100
#define MINLEVEL    4
#define AVALY       140
#define XNOME       100
#define YNOME       60
#define NCOLORS     16
#define COLORSYCORR 20
#define NMBRCOLORS  8
#define COLORCORR   10
#define PLAYX       -100
#define YPERPLAY    51
#define MAXNPLAYS   9
